# Generated by Django 5.2.17 on 2026-08-09 17:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ledger", "0003_transaction_card_label_transaction_needs_review_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortcutCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("token_prefix", models.CharField(max_length=16, unique=True)),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("scope_mask", models.PositiveSmallIntegerField(default=7)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "tracker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shortcut_credentials",
                        to="ledger.tracker",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortcut_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="ShortcutIdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_records",
                        to="shortcut.shortcutcredential",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shortcut_idempotency_records",
                        to="ledger.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortcut_idempotency_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddIndex(
            model_name="shortcutcredential",
            index=models.Index(
                fields=["user", "revoked_at", "expires_at"],
                name="shortcut_sh_user_id_38477c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="shortcutcredential",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_mask__gt", 0), ("scope_mask__lte", 7)),
                name="shortcut_scope_mask_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="shortcutcredential",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expires_at__isnull", True),
                    ("expires_at__gt", models.F("created_at")),
                    _connector="OR",
                ),
                name="shortcut_expiry_after_creation",
            ),
        ),
        migrations.AddIndex(
            model_name="shortcutidempotencyrecord",
            index=models.Index(
                fields=["credential", "expires_at"],
                name="shortcut_sh_credent_89851b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="shortcutidempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("user", "key"),
                name="unique_shortcut_idempotency_key_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="shortcutidempotencyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="shortcut_idempotency_expiry_after_creation",
            ),
        ),
    ]
