from __future__ import annotations

from collections.abc import Callable
from datetime import UTC, date, datetime, time
from uuid import UUID, uuid4

import pytest
from rest_framework.test import APIClient

from apps.audit.models import AuditEvent
from apps.ledger.models import Account, Category, TrackerMembership, Transaction
from apps.planning.models import RecurringOccurrence, RecurringRule, RecurringRuleRevision
from apps.planning.services.recurrence import (
    materialize_due_rules,
    materialize_rule,
    next_due_date,
    occurrence_key,
    scheduled_utc,
)
from apps.planning.tasks import materialize_recurring_rules
from apps.users.models import User

pytestmark = pytest.mark.django_db


def _tracker(client: APIClient, *, currency: str = "EUR") -> dict[str, object]:
    response = client.post(
        "/api/v1/trackers/",
        {"name": "Recurring household", "base_currency": currency},
        format="json",
    )
    assert response.status_code == 201, response.data
    return response.data


def _account(client: APIClient, tracker_id: object, *, currency: str = "EUR") -> object:
    response = client.post(
        "/api/v1/accounts/",
        {
            "tracker_id": tracker_id,
            "name": f"{currency} recurring account",
            "type": "checking",
            "currency": currency,
            "opening_balance_minor": 100_000,
            "opening_date": "2026-01-01",
        },
        format="json",
    )
    assert response.status_code == 201, response.data
    return response.data["id"]


def _rule_payload(
    tracker_id: object,
    account_id: object,
    *,
    starts_on: str = "2026-01-31",
    next_due_on: str | None = None,
    ends_on: str | None = None,
    cadence: str = "monthly",
    category_id: object | None = None,
    is_subscription: bool = False,
) -> dict[str, object]:
    return {
        "tracker_id": tracker_id,
        "name": "Internet plan" if is_subscription else "Household supplies",
        "kind": "expense",
        "is_subscription": is_subscription,
        "amount_minor": 2_500,
        "currency": "EUR",
        "account_id": account_id,
        "category_id": category_id,
        "merchant": "Example Provider",
        "note": "Generated by a recurring rule",
        "cadence": cadence,
        "custom_interval_unit": "",
        "custom_interval_count": 1,
        "time_zone": "Europe/Tirane",
        "starts_on": starts_on,
        "ends_on": ends_on,
        "local_time": "09:30:00",
        "next_due_on": next_due_on or starts_on,
        "subscription_provider": "Example Provider" if is_subscription else "",
        "trial_ends_on": None,
        "cancellation_url": "https://example.test/cancel" if is_subscription else "",
        "subscription_note": "Annual review" if is_subscription else "",
    }


def _create_rule(client: APIClient, payload: dict[str, object], *, subscription=False):
    resource = "subscriptions" if subscription else "recurring-rules"
    response = client.post(f"/api/v1/{resource}/", payload, format="json")
    assert response.status_code == 201, response.data
    return response


def _sync_payload(
    rule_id: UUID, tracker_id: UUID, account_id: UUID, category_id: UUID
) -> dict[str, object]:
    return {
        "client_payload_version": 1,
        "id": str(rule_id),
        "tracker_id": str(tracker_id),
        "name": "Offline recurring groceries",
        "kind": "expense",
        "is_subscription": False,
        "amount_minor": 3_500,
        "currency": "EUR",
        "currency_exponent": 2,
        "account_id": str(account_id),
        "account_amount_minor": 3_500,
        "category_id": str(category_id),
        "merchant": "Offline Market",
        "note": "",
        "base_amount_minor": 3_500,
        "base_currency": "EUR",
        "rate_snapshot": "1.000000000000",
        "rate_source": "identity",
        "rate_effective_at": "2026-08-01T07:30:00Z",
        "cadence": "monthly",
        "custom_interval_unit": "",
        "custom_interval_count": 1,
        "time_zone": "Europe/Tirane",
        "starts_on": "2026-08-01",
        "ends_on": None,
        "local_time": "09:30:00",
        "next_due_on": "2026-08-01",
        "subscription_provider": "",
        "trial_ends_on": None,
        "cancellation_url": "",
        "subscription_note": "",
        "archived_at": None,
        "deleted_at": None,
    }


def _sync_operation(
    rule_id: UUID,
    payload: dict[str, object],
    *,
    command: str,
    base_version: int | None,
    operation_id: UUID | None = None,
) -> dict[str, object]:
    return {
        "operation_id": str(operation_id or uuid4()),
        "local_sequence": 1,
        "entity_type": "recurring_rule",
        "entity_id": str(rule_id),
        "command": command,
        "base_server_version": base_version,
        "payload": payload,
    }


def _push(client: APIClient, operation: dict[str, object]):
    return client.post(
        "/api/v1/sync/push",
        {"protocol_version": 1, "operations": [operation]},
        format="json",
    )


def test_calendar_schedule_preserves_anchors_and_resolves_dst() -> None:
    spring = scheduled_utc(date(2026, 3, 29), time(2, 30), "Europe/Tirane")
    assert spring == datetime(2026, 3, 29, 1, 0, tzinfo=UTC)
    autumn = scheduled_utc(date(2026, 10, 25), time(2, 30), "Europe/Tirane")
    assert autumn == datetime(2026, 10, 25, 0, 30, tzinfo=UTC)

    monthly = RecurringRule(
        cadence=RecurringRule.Cadence.MONTHLY,
        anchor_day=31,
        anchor_month=1,
    )
    assert next_due_date(monthly, date(2027, 1, 31)) == date(2027, 2, 28)
    assert next_due_date(monthly, date(2027, 2, 28)) == date(2027, 3, 31)

    yearly = RecurringRule(
        cadence=RecurringRule.Cadence.YEARLY,
        anchor_day=29,
        anchor_month=2,
    )
    assert next_due_date(yearly, date(2024, 2, 29)) == date(2025, 2, 28)
    assert next_due_date(yearly, date(2027, 2, 28)) == date(2028, 2, 29)

    custom = RecurringRule(
        cadence=RecurringRule.Cadence.CUSTOM,
        custom_interval_unit=RecurringRule.IntervalUnit.MONTH,
        custom_interval_count=2,
        anchor_day=31,
        anchor_month=1,
    )
    assert next_due_date(custom, date(2026, 1, 31)) == date(2026, 3, 31)


def test_celery_task_delegates_to_the_bounded_materializer(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    expected = {
        "rules_considered": 2,
        "posted": 3,
        "skipped": 1,
        "failed": 0,
        "remaining_due_rules": 0,
    }
    monkeypatch.setattr("apps.planning.tasks.materialize_due_rules", lambda: expected)
    assert materialize_recurring_rules.run() == expected


def test_recurring_crud_roles_revisions_subscription_and_strict_validation(
    user: User,
    client_for_user: Callable[[User, str], APIClient],
) -> None:
    client = client_for_user(user, "Valid-Test-Password-8274!")
    tracker = _tracker(client)
    account_id = _account(client, tracker["id"])
    groceries = Category.objects.get(tracker_id=tracker["id"], name="Groceries")
    payload = _rule_payload(tracker["id"], account_id, category_id=groceries.id)
    created = _create_rule(client, payload)
    assert created.data["currency_exponent"] == 2
    assert created.data["base_amount_minor"] == 2_500
    assert created.data["rate_snapshot"] == "1.000000000000"
    rendered_due = datetime.fromisoformat(created.data["next_due_at"])
    assert rendered_due.astimezone(UTC) == datetime(2026, 1, 31, 8, 30, tzinfo=UTC)
    assert AuditEvent.objects.filter(
        action="recurring.rule_created", target_id=created.data["id"]
    ).exists()

    viewer = User.objects.create_user(
        email="recurring-viewer@example.test", password="Viewer-Test-Password-8274!"
    )
    TrackerMembership.objects.create(
        tracker_id=tracker["id"],
        user=viewer,
        role=TrackerMembership.Role.VIEWER,
        state=TrackerMembership.State.ACTIVE,
    )
    viewer_client = client_for_user(viewer, "Viewer-Test-Password-8274!")
    assert viewer_client.get(f"/api/v1/recurring-rules/{created.data['id']}/").status_code == 200
    assert viewer_client.post("/api/v1/recurring-rules/", payload, format="json").status_code == 403

    updated_payload = {**payload, "amount_minor": 3_000, "base_version": created.data["version"]}
    updated = client.put(
        f"/api/v1/recurring-rules/{created.data['id']}/", updated_payload, format="json"
    )
    assert updated.status_code == 200, updated.data
    assert updated.data["amount_minor"] == 3_000
    revision = RecurringRuleRevision.objects.get(rule_id=created.data["id"])
    assert revision.amount_minor == 2_500
    stale = client.put(
        f"/api/v1/recurring-rules/{created.data['id']}/", updated_payload, format="json"
    )
    assert stale.status_code == 409

    subscription_payload = _rule_payload(
        tracker["id"], account_id, starts_on="2026-08-15", is_subscription=True
    )
    subscription = _create_rule(client, subscription_payload, subscription=True)
    assert subscription.data["renewal_date"] == "2026-08-15"
    assert len(client.get("/api/v1/subscriptions/").data["results"]) == 1
    missing_provider = {**subscription_payload, "subscription_provider": ""}
    assert client.post("/api/v1/subscriptions/", missing_provider, format="json").status_code == 400
    unsafe_url = {**subscription_payload, "cancellation_url": "http://example.test/cancel"}
    assert client.post("/api/v1/subscriptions/", unsafe_url, format="json").status_code == 400
    unknown = {**payload, "silent_reconcile": True}
    assert client.post("/api/v1/recurring-rules/", unknown, format="json").status_code == 400


def test_downtime_catchup_is_bounded_idempotent_and_does_not_rewrite_history(
    user: User,
    client_for_user: Callable[[User, str], APIClient],
) -> None:
    client = client_for_user(user, "Valid-Test-Password-8274!")
    tracker = _tracker(client)
    account_id = _account(client, tracker["id"])
    groceries = Category.objects.get(tracker_id=tracker["id"], name="Groceries")
    created = _create_rule(
        client,
        _rule_payload(tracker["id"], account_id, category_id=groceries.id),
    )
    rule_id = created.data["id"]
    through = datetime(2026, 4, 1, tzinfo=UTC)

    first = materialize_rule(rule_id, through=through, maximum=2)
    assert first.posted == 2
    assert first.remaining_due is True
    second = materialize_due_rules(through=through)
    assert second == {
        "rules_considered": 1,
        "posted": 1,
        "skipped": 0,
        "failed": 0,
        "remaining_due_rules": 0,
    }
    assert list(
        RecurringOccurrence.objects.filter(rule_id=rule_id)
        .order_by("due_on")
        .values_list("due_on", flat=True)
    ) == [date(2026, 1, 31), date(2026, 2, 28), date(2026, 3, 31)]
    transactions = Transaction.objects.filter(source=Transaction.Source.RECURRING).order_by(
        "occurred_at"
    )
    assert transactions.count() == 3
    assert len(set(transactions.values_list("id", flat=True))) == 3
    assert all(record.status == Transaction.Status.POSTED for record in transactions)
    assert all(record.allocations.get().amount_minor == 2_500 for record in transactions)
    assert materialize_due_rules(through=through)["posted"] == 0
    assert Transaction.objects.filter(source=Transaction.Source.RECURRING).count() == 3

    update = _rule_payload(
        tracker["id"],
        account_id,
        starts_on="2026-01-31",
        next_due_on="2026-04-30",
        category_id=groceries.id,
    )
    update.update(amount_minor=4_000, base_version=RecurringRule.objects.get(id=rule_id).version)
    response = client.put(f"/api/v1/recurring-rules/{rule_id}/", update, format="json")
    assert response.status_code == 200, response.data
    assert set(transactions.values_list("amount_minor", flat=True)) == {2_500}


def test_pause_skip_resume_end_and_failed_occurrence_recovery(
    user: User,
    client_for_user: Callable[[User, str], APIClient],
) -> None:
    client = client_for_user(user, "Valid-Test-Password-8274!")
    tracker = _tracker(client)
    account_id = _account(client, tracker["id"])
    created = _create_rule(
        client,
        _rule_payload(tracker["id"], account_id, starts_on="2026-08-01"),
    )
    rule_id = created.data["id"]
    paused = client.post(
        f"/api/v1/recurring-rules/{rule_id}/pause/",
        {"base_version": created.data["version"]},
        format="json",
    )
    assert paused.status_code == 200, paused.data
    assert materialize_rule(rule_id, through=datetime(2026, 9, 1, tzinfo=UTC)).posted == 0

    skipped = client.post(
        f"/api/v1/recurring-rules/{rule_id}/skip-next/",
        {"base_version": paused.data["version"]},
        format="json",
    )
    assert skipped.status_code == 200, skipped.data
    assert skipped.data["state"] == "skipped"
    assert skipped.data["occurrence_key"] == occurrence_key(
        RecurringRule.objects.get(id=rule_id).id, date(2026, 8, 1)
    )
    rule = RecurringRule.objects.get(id=rule_id)
    resumed = client.post(
        f"/api/v1/recurring-rules/{rule_id}/resume/",
        {"base_version": rule.version},
        format="json",
    )
    assert resumed.status_code == 200, resumed.data
    result = materialize_rule(rule.id, through=datetime(2026, 9, 2, tzinfo=UTC))
    assert result.posted == 1
    assert RecurringOccurrence.objects.filter(rule_id=rule_id, state="skipped").count() == 1

    rule.refresh_from_db()
    ended = client.post(
        f"/api/v1/recurring-rules/{rule_id}/end/",
        {"base_version": rule.version},
        format="json",
    )
    assert ended.status_code == 200
    assert ended.data["state"] == "ended"
    assert ended.data["renewal_date"] is None

    failing = _create_rule(
        client,
        _rule_payload(tracker["id"], account_id, starts_on="2026-10-01"),
    )
    account = Account.objects.get(id=account_id)
    account.archived_at = datetime(2026, 9, 1, tzinfo=UTC)
    account.save(update_fields=("archived_at", "updated_at"))
    failure = materialize_rule(failing.data["id"], through=datetime(2026, 10, 2, tzinfo=UTC))
    assert failure.failed == 1
    failed_occurrence = RecurringOccurrence.objects.get(rule_id=failing.data["id"])
    assert failed_occurrence.state == "failed"
    assert failed_occurrence.error_code == "materialization_validation_error"
    assert failed_occurrence.transaction is None
    failed_id = failed_occurrence.id

    account.archived_at = None
    account.save(update_fields=("archived_at", "updated_at"))
    recovered = materialize_rule(failing.data["id"], through=datetime(2026, 10, 2, tzinfo=UTC))
    assert recovered.posted == 1
    failed_occurrence.refresh_from_db()
    assert failed_occurrence.id == failed_id
    assert failed_occurrence.state == "posted"
    assert failed_occurrence.version == 2


def test_cross_currency_rule_requires_consistent_snapshots(
    user: User,
    client_for_user: Callable[[User, str], APIClient],
) -> None:
    client = client_for_user(user, "Valid-Test-Password-8274!")
    tracker = _tracker(client, currency="EUR")
    usd_account = _account(client, tracker["id"], currency="USD")
    payload = _rule_payload(tracker["id"], usd_account, starts_on="2026-08-09")
    payload["currency"] = "USD"
    payload.update(
        base_amount_minor=2_000,
        base_currency="EUR",
        rate_snapshot="0.800000000000",
        rate_source="manual-template",
        rate_effective_at="2026-08-09T10:00:00Z",
    )
    accepted = _create_rule(client, payload)
    assert accepted.data["base_amount_minor"] == 2_000
    wrong = {**payload, "rate_snapshot": "0.810000000000"}
    assert client.post("/api/v1/recurring-rules/", wrong, format="json").status_code == 400


def test_recurring_sync_replay_state_commands_conflict_bootstrap_and_tombstone(
    user: User,
    client_for_user: Callable[[User, str], APIClient],
) -> None:
    client = client_for_user(user, "Valid-Test-Password-8274!")
    tracker = _tracker(client)
    account_id = _account(client, tracker["id"])
    groceries = Category.objects.get(tracker_id=tracker["id"], name="Groceries")
    rule_id = uuid4()
    payload = _sync_payload(
        rule_id,
        UUID(str(tracker["id"])),
        UUID(str(account_id)),
        groceries.id,
    )
    create_operation = _sync_operation(
        rule_id,
        payload,
        command="create",
        base_version=None,
    )
    created = _push(client, create_operation)
    assert created.status_code == 200, created.data
    result = created.data["results"][0]
    assert result["status"] == "accepted"
    assert result["representation"]["state"] == "active"
    assert result["server_version"] == 1
    replay = _push(client, create_operation)
    assert replay.data["results"][0]["status"] == "duplicate"
    assert RecurringRule.objects.filter(id=rule_id).count() == 1

    paused = _push(
        client,
        _sync_operation(rule_id, payload, command="pause", base_version=1),
    )
    pause_result = paused.data["results"][0]
    assert pause_result["status"] == "accepted"
    assert pause_result["representation"]["state"] == "paused"

    skipped = _push(
        client,
        _sync_operation(
            rule_id,
            payload,
            command="skip_next",
            base_version=pause_result["server_version"],
        ),
    )
    skip_result = skipped.data["results"][0]
    assert skip_result["status"] == "accepted"
    assert skip_result["representation"]["next_due_on"] == "2026-09-01"
    occurrence = RecurringOccurrence.objects.get(rule_id=rule_id)
    assert occurrence.state == RecurringOccurrence.State.SKIPPED

    stale_payload = {**payload, "amount_minor": 4_000, "account_amount_minor": 4_000}
    stale = _push(
        client,
        _sync_operation(rule_id, stale_payload, command="update", base_version=1),
    )
    assert stale.data["results"][0]["status"] == "conflict"
    assert stale.data["results"][0]["representation"]["amount_minor"] == 3_500

    bootstrap = client.get("/api/v1/sync/bootstrap?limit=500")
    assert bootstrap.status_code == 200, bootstrap.data
    assert [item["id"] for item in bootstrap.data["data"]["recurring_rules"]] == [str(rule_id)]
    assert bootstrap.data["data"]["recurring_occurrences"][0]["id"] == str(occurrence.id)

    current_version = RecurringRule.objects.get(id=rule_id).version
    deleted = _push(
        client,
        _sync_operation(rule_id, payload, command="delete", base_version=current_version),
    )
    delete_result = deleted.data["results"][0]
    assert delete_result["status"] == "accepted"
    assert delete_result["representation"]["deleted_at"] is not None
