# Generated by Django 5.2.17 on 2026-08-09 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0002_allocationrevision_category_version_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRetentionState',
            fields=[
                ('key', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('minimum_sequence', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncDeviceState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_ack_sequence', models.PositiveBigIntegerField(default=0)),
                ('last_ack_at', models.DateTimeField(blank=True, null=True)),
                ('device_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='users.devicesession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncChange',
            fields=[
                ('sequence', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('tracker', 'Tracker'), ('tracker_membership', 'Tracker membership'), ('account', 'Account'), ('category', 'Category'), ('tag', 'Tag'), ('merchant', 'Merchant'), ('transaction', 'Transaction')], max_length=32)),
                ('entity_id', models.UUIDField()),
                ('operation', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], max_length=12)),
                ('version', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('audience_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_sync_changes', to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_changes', to='ledger.tracker')),
            ],
            options={
                'ordering': ('sequence',),
                'indexes': [models.Index(fields=['tracker', 'sequence'], name='sync_syncch_tracker_c520f1_idx'), models.Index(fields=['audience_user', 'sequence'], name='sync_syncch_audienc_6192ea_idx'), models.Index(fields=['entity_type', 'entity_id', 'sequence'], name='sync_syncch_entity__9d57e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncOperationReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_id', models.UUIDField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('entity_type', models.CharField(choices=[('tracker', 'Tracker'), ('tracker_membership', 'Tracker membership'), ('account', 'Account'), ('category', 'Category'), ('tag', 'Tag'), ('merchant', 'Merchant'), ('transaction', 'Transaction')], max_length=32)),
                ('entity_id', models.UUIDField()),
                ('state', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=12)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('device_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_operation_receipts', to='users.devicesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operation_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='sync_syncop_user_id_5ebfde_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'operation_id'), name='unique_sync_operation_per_user')],
            },
        ),
    ]
