# Generated by Django 5.2.17 on 2026-08-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncchange',
            name='entity_type',
            field=models.CharField(choices=[('tracker', 'Tracker'), ('tracker_membership', 'Tracker membership'), ('account', 'Account'), ('category', 'Category'), ('tag', 'Tag'), ('merchant', 'Merchant'), ('budget', 'Budget'), ('transaction', 'Transaction')], max_length=32),
        ),
        migrations.AlterField(
            model_name='syncoperationreceipt',
            name='entity_type',
            field=models.CharField(choices=[('tracker', 'Tracker'), ('tracker_membership', 'Tracker membership'), ('account', 'Account'), ('category', 'Category'), ('tag', 'Tag'), ('merchant', 'Merchant'), ('budget', 'Budget'), ('transaction', 'Transaction')], max_length=32),
        ),
    ]
