# Generated by Django 5.2.17 on 2026-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_alter_syncchange_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncchange',
            name='entity_type',
            field=models.CharField(choices=[('tracker', 'Tracker'), ('tracker_membership', 'Tracker membership'), ('account', 'Account'), ('category', 'Category'), ('tag', 'Tag'), ('merchant', 'Merchant'), ('budget', 'Budget'), ('recurring_rule', 'Recurring rule'), ('recurring_occurrence', 'Recurring occurrence'), ('installment_plan', 'Installment plan'), ('installment_schedule_item', 'Installment schedule item'), ('installment_payment', 'Installment payment'), ('participant', 'Participant'), ('settlement', 'Settlement'), ('transaction', 'Transaction'), ('attachment', 'Attachment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='syncoperationreceipt',
            name='entity_type',
            field=models.CharField(choices=[('tracker', 'Tracker'), ('tracker_membership', 'Tracker membership'), ('account', 'Account'), ('category', 'Category'), ('tag', 'Tag'), ('merchant', 'Merchant'), ('budget', 'Budget'), ('recurring_rule', 'Recurring rule'), ('recurring_occurrence', 'Recurring occurrence'), ('installment_plan', 'Installment plan'), ('installment_schedule_item', 'Installment schedule item'), ('installment_payment', 'Installment payment'), ('participant', 'Participant'), ('settlement', 'Settlement'), ('transaction', 'Transaction'), ('attachment', 'Attachment')], max_length=32),
        ),
    ]
