# Generated by Django 5.2.17 on 2026-08-13 17:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0004_participant_settlement_splitpayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('original_filename', models.CharField(max_length=180)),
                ('content_type', models.CharField(choices=[('image/jpeg', 'JPEG image'), ('image/png', 'PNG image'), ('image/heic', 'HEIC image'), ('image/heif', 'HEIF image'), ('image/webp', 'WebP image'), ('application/pdf', 'PDF document')], max_length=32)),
                ('byte_count', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Must be a lowercase SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('storage_key', models.CharField(blank=True, editable=False, max_length=255)),
                ('upload_state', models.CharField(choices=[('pending', 'Pending upload'), ('ready', 'Ready'), ('quarantined', 'Quarantined')], default='pending', max_length=16)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('not_configured', 'Not configured'), ('clean', 'Clean'), ('blocked', 'Blocked'), ('error', 'Scanner error')], default='pending', max_length=24)),
                ('original_retained', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments_created', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments_last_edited', to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='ledger.tracker')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='ledger.transaction')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tracker', 'deleted_at', 'created_at'], name='attachments_tracker_6a818a_idx'), models.Index(fields=['transaction', 'deleted_at'], name='attachments_transac_e23350_idx'), models.Index(fields=['upload_state', 'created_at'], name='attachments_upload__8431a0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('byte_count__gt', 0)), name='attachment_byte_count_positive'), models.UniqueConstraint(condition=models.Q(('storage_key', ''), _negated=True), fields=('storage_key',), name='attachment_storage_key_unique_when_set')],
            },
        ),
    ]
