# Generated by Django 5.2.17 on 2026-08-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='deleted_with_transaction',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
