# Generated by Django 5.2.17 on 2026-08-09 13:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(editable=False, max_length=120)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('checking', 'Checking / bank'), ('savings', 'Savings'), ('credit', 'Credit'), ('digital_wallet', 'Digital wallet'), ('custom', 'Custom')], max_length=24)),
                ('currency', models.CharField(max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField()),
                ('opening_balance_minor', models.BigIntegerField(default=0)),
                ('opening_date', models.DateField()),
                ('color', models.CharField(default='#3663F5', max_length=16)),
                ('icon', models.CharField(default='banknote', max_length=80)),
                ('include_in_net_worth', models.BooleanField(default=True)),
                ('credit_limit_minor', models.PositiveBigIntegerField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(editable=False, max_length=120)),
                ('icon', models.CharField(default='square.grid.2x2', max_length=80)),
                ('color', models.CharField(default='#73819B', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.category')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('icon', models.CharField(default='wallet.pass', max_length=80)),
                ('color', models.CharField(default='#3663F5', max_length=16)),
                ('base_currency', models.CharField(default='ALL', max_length=3)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_trackers', to='ledger.account')),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_trackers', to='ledger.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=80)),
                ('normalized_name', models.CharField(editable=False, max_length=80)),
                ('color', models.CharField(default='#73819B', max_length=16)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ledger.tracker')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('display_name', models.CharField(max_length=160)),
                ('normalized_name', models.CharField(editable=False, max_length=160)),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_merchants', to='ledger.category')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='ledger.tracker')),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ledger.tracker'),
        ),
        migrations.AddField(
            model_name='account',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='ledger.tracker'),
        ),
        migrations.CreateModel(
            name='TrackerInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=12)),
                ('token_prefix', models.CharField(max_length=16, unique=True)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_invites_accepted', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracker_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='ledger.tracker')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrackerMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=12)),
                ('state', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=12)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ledger.tracker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer'), ('settlement', 'Settlement'), ('refund', 'Refund / adjustment')], max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('shortcut', 'Shortcut'), ('recurring', 'Recurring'), ('installment', 'Installment'), ('receipt_scan', 'Receipt scan'), ('import', 'Import'), ('server', 'Server')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending', 'Pending'), ('voided', 'Voided'), ('reconciled', 'Reconciled')], default='posted', max_length=16)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField()),
                ('base_amount_minor', models.PositiveBigIntegerField()),
                ('base_currency', models.CharField(max_length=3)),
                ('rate_snapshot', models.DecimalField(decimal_places=12, max_digits=28)),
                ('rate_source', models.CharField(max_length=80)),
                ('rate_effective_at', models.DateTimeField()),
                ('payee', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField(blank=True, max_length=5000)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('external_event_id', models.UUIDField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_edited', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ledger.merchant')),
                ('refund_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='ledger.transaction')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.tracker')),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CategoryAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ledger.category')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ledger.transaction')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AccountMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('signed_amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField()),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='ledger.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='ledger.transaction')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransactionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_version', models.PositiveBigIntegerField()),
                ('reason', models.CharField(max_length=24)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer'), ('settlement', 'Settlement'), ('refund', 'Refund / adjustment')], max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('shortcut', 'Shortcut'), ('recurring', 'Recurring'), ('installment', 'Installment'), ('receipt_scan', 'Receipt scan'), ('import', 'Import'), ('server', 'Server')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending', 'Pending'), ('voided', 'Voided'), ('reconciled', 'Reconciled')], max_length=16)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField()),
                ('base_amount_minor', models.PositiveBigIntegerField()),
                ('base_currency', models.CharField(max_length=3)),
                ('rate_snapshot', models.DecimalField(decimal_places=12, max_digits=28)),
                ('rate_source', models.CharField(max_length=80)),
                ('rate_effective_at', models.DateTimeField()),
                ('payee', models.CharField(blank=True, max_length=160)),
                ('occurred_at', models.DateTimeField()),
                ('external_event_id', models.UUIDField(blank=True, null=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_revisions_recorded', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_revisions', to='ledger.merchant')),
                ('refund_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_link_revisions', to='ledger.transaction')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='ledger.transaction')),
            ],
            options={
                'ordering': ('-recorded_version',),
            },
        ),
        migrations.CreateModel(
            name='MovementRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField()),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_revisions', to='ledger.account')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='ledger.transactionrevision')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AllocationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_revisions', to='ledger.category')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ledger.transactionrevision')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_tags', to='ledger.tag')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='ledger.transaction')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['owner', 'archived_at'], name='ledger_trac_owner_i_a63a48_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tracker', 'normalized_name'), name='unique_tag_name_per_tracker'),
        ),
        migrations.AddConstraint(
            model_name='merchant',
            constraint=models.UniqueConstraint(fields=('tracker', 'normalized_name'), name='unique_merchant_per_tracker'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='category_not_own_parent'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('tracker__isnull', False)), fields=('tracker', 'kind', 'normalized_name'), name='unique_tracker_category_name_kind'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('tracker__isnull', True)), fields=('kind', 'normalized_name'), name='unique_global_category_name_kind'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('tracker', 'normalized_name'), name='unique_account_name_per_tracker'),
        ),
        migrations.AddIndex(
            model_name='trackerinvite',
            index=models.Index(fields=['tracker', 'email', 'expires_at'], name='ledger_trac_tracker_b48b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='trackermembership',
            index=models.Index(fields=['user', 'state', 'deleted_at'], name='ledger_trac_user_id_a23014_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackermembership',
            constraint=models.UniqueConstraint(fields=('tracker', 'user'), name='unique_tracker_user'),
        ),
        migrations.AddConstraint(
            model_name='trackermembership',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('role', 'owner'), ('state', 'active')), fields=('tracker',), name='one_active_owner_membership'),
        ),
        migrations.AddConstraint(
            model_name='trackermembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'owner'), _negated=True), ('state', 'active'), _connector='OR'), name='owner_membership_is_active'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tracker', 'occurred_at'], name='ledger_tran_tracker_b26e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tracker', 'status', 'deleted_at'], name='ledger_tran_tracker_64a693_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='transaction_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount_minor__gt', 0)), name='transaction_base_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('refund_of_id')), _negated=True), name='transaction_not_own_refund'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id__isnull', False)), fields=('tracker', 'source', 'external_event_id'), name='unique_external_event_per_tracker_source'),
        ),
        migrations.AddConstraint(
            model_name='categoryallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='allocation_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='categoryallocation',
            constraint=models.UniqueConstraint(fields=('transaction', 'category'), name='unique_category_per_transaction'),
        ),
        migrations.AddConstraint(
            model_name='accountmovement',
            constraint=models.CheckConstraint(condition=models.Q(('signed_amount_minor', 0), _negated=True), name='movement_amount_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='accountmovement',
            constraint=models.UniqueConstraint(fields=('transaction', 'account'), name='unique_account_per_transaction'),
        ),
        migrations.AddConstraint(
            model_name='transactionrevision',
            constraint=models.UniqueConstraint(fields=('transaction', 'recorded_version'), name='unique_transaction_recorded_version'),
        ),
        migrations.AddConstraint(
            model_name='transactiontag',
            constraint=models.UniqueConstraint(fields=('transaction', 'tag'), name='unique_tag_per_transaction'),
        ),
    ]
