# Generated by Django 5.2.17 on 2026-08-09 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrevision',
            name='category_version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='categoryallocation',
            name='category_version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CategoryRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_version', models.PositiveBigIntegerField()),
                ('reason', models.CharField(max_length=24)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=16)),
                ('sort_order', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='ledger.category')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_revisions_recorded', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_category_revisions', to='ledger.category')),
            ],
            options={
                'ordering': ('-recorded_version',),
                'constraints': [models.UniqueConstraint(fields=('category', 'recorded_version'), name='unique_category_recorded_version')],
            },
        ),
    ]
