# Generated by Django 5.2.17 on 2026-08-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0002_allocationrevision_category_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="card_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="transaction",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transactionrevision",
            name="card_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="transactionrevision",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
    ]
