# Generated by Django 5.2.17 on 2026-08-13 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_registered_participants(apps, schema_editor):
    participant_model = apps.get_model("ledger", "Participant")
    membership_model = apps.get_model("ledger", "TrackerMembership")
    profile_model = apps.get_model("users", "Profile")
    database = schema_editor.connection.alias
    profile_names = {
        profile.user_id: profile.display_name.strip()
        for profile in profile_model.objects.using(database).all()
    }
    memberships = (
        membership_model.objects.using(database)
        .filter(state="active", deleted_at__isnull=True)
        .select_related("user")
    )
    for membership in memberships.iterator():
        display_name = profile_names.get(membership.user_id) or membership.user.email
        display_name = display_name[:120]
        participant_model.objects.using(database).get_or_create(
            tracker_id=membership.tracker_id,
            linked_user_id=membership.user_id,
            defaults={
                "display_name": display_name,
                "normalized_name": " ".join(display_name.split()).casefold(),
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0003_transaction_card_label_transaction_needs_review_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("display_name", models.CharField(max_length=120)),
                ("normalized_name", models.CharField(editable=False, max_length=120)),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "linked_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracker_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="ledger.tracker",
                    ),
                ),
            ],
            options={
                "ordering": ("display_name", "id"),
            },
        ),
        migrations.RunPython(
            backfill_registered_participants,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("currency_exponent", models.PositiveSmallIntegerField()),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("note", models.TextField(blank=True, max_length=5000)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements_sent",
                        to="ledger.participant",
                    ),
                ),
                (
                    "last_editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements_received",
                        to="ledger.participant",
                    ),
                ),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="ledger.tracker",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_record",
                        to="ledger.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="SplitPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("amount_minor", models.PositiveBigIntegerField()),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="split_payments",
                        to="ledger.participant",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_payments",
                        to="ledger.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ("participant_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="SplitPaymentRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_minor", models.PositiveBigIntegerField()),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="split_payment_revisions",
                        to="ledger.participant",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_payments",
                        to="ledger.transactionrevision",
                    ),
                ),
            ],
            options={
                "ordering": ("participant_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="SplitShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("amount_minor", models.PositiveBigIntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("equal", "Equal"),
                            ("exact", "Exact amounts"),
                            ("percentage", "Percentages"),
                        ],
                        max_length=16,
                    ),
                ),
                ("percentage_basis_points", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="split_shares",
                        to="ledger.participant",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_shares",
                        to="ledger.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ("participant_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="SplitShareRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_minor", models.PositiveBigIntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("equal", "Equal"),
                            ("exact", "Exact amounts"),
                            ("percentage", "Percentages"),
                        ],
                        max_length=16,
                    ),
                ),
                ("percentage_basis_points", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="split_share_revisions",
                        to="ledger.participant",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_shares",
                        to="ledger.transactionrevision",
                    ),
                ),
            ],
            options={
                "ordering": ("participant_id", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["tracker", "archived_at", "deleted_at"],
                name="ledger_part_tracker_542ad4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.CheckConstraint(
                condition=models.Q(("normalized_name", ""), _negated=True),
                name="participant_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("linked_user__isnull", False)),
                fields=("tracker", "linked_user"),
                name="unique_linked_participant_per_tracker",
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("linked_user__isnull", True)),
                fields=("tracker", "normalized_name"),
                name="unique_guest_participant_name_per_tracker",
            ),
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(
                fields=["tracker", "currency", "deleted_at"], name="ledger_sett_tracker_ef5c6d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_minor__gt", 0)), name="settlement_amount_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_participant", models.F("to_participant")), _negated=True),
                name="settlement_distinct_participants",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_minor__gt", 0)), name="split_payment_amount_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="splitpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("transaction", "participant"),
                name="unique_active_split_payment_participant",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_minor__gt", 0)), name="split_share_amount_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="splitshare",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("method", "percentage"),
                        ("percentage_basis_points__gt", 0),
                        ("percentage_basis_points__lte", 10000),
                    ),
                    models.Q(
                        ("method__in", ("equal", "exact")),
                        ("percentage_basis_points__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="split_share_percentage_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitshare",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("transaction", "participant"),
                name="unique_active_split_share_participant",
            ),
        ),
    ]
