# Generated by Django 5.2.17 on 2026-08-21 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_participant_settlement_splitpayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('full', 'Full JSON')], max_length=12)),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], default='ready', max_length=12)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('storage_key', models.CharField(max_length=160, unique=True)),
                ('byte_count', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('content_type', models.CharField(blank=True, max_length=80)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('error_summary', models.CharField(blank=True, max_length=240)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to='ledger.tracker')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['requester', 'created_at'], name='ledger_expo_request_50e90e_idx'), models.Index(fields=['tracker', 'state', 'expires_at'], name='ledger_expo_tracker_138bbf_idx')],
            },
        ),
    ]
