# Generated by Django 5.2.17 on 2026-08-09 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0003_transaction_card_label_transaction_needs_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('tracker', 'Entire tracker'), ('categories', 'Selected categories')], max_length=16)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('custom', 'Custom range')], max_length=16)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField()),
                ('time_zone', models.CharField(max_length=64)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('rollover', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets_created', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets_edited', to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='ledger.tracker')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name_snapshot', models.CharField(max_length=120)),
                ('category_version_snapshot', models.PositiveBigIntegerField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='planning.budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_links', to='ledger.category')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='categories',
            field=models.ManyToManyField(related_name='budgets', through='planning.BudgetCategory', to='ledger.category'),
        ),
        migrations.CreateModel(
            name='BudgetThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percent', models.PositiveSmallIntegerField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='planning.budget')),
            ],
            options={
                'ordering': ('percent',),
            },
        ),
        migrations.AddConstraint(
            model_name='budgetcategory',
            constraint=models.UniqueConstraint(fields=('budget', 'category'), name='unique_budget_category'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['tracker', 'archived_at', 'deleted_at'], name='planning_bu_tracker_dfd260_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['tracker', 'starts_on', 'ends_on'], name='planning_bu_tracker_ee346b_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='budget_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='budget_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('period', 'custom'), _negated=True), ('ends_on__isnull', False), _connector='OR'), name='custom_budget_has_end'),
        ),
        migrations.AddConstraint(
            model_name='budgetthreshold',
            constraint=models.UniqueConstraint(fields=('budget', 'percent'), name='unique_budget_threshold'),
        ),
        migrations.AddConstraint(
            model_name='budgetthreshold',
            constraint=models.CheckConstraint(condition=models.Q(('percent__gte', 1), ('percent__lte', 1000)), name='budget_threshold_between_1_and_1000'),
        ),
    ]
