# Generated by Django 5.2.17 on 2026-08-09 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_transaction_card_label_transaction_needs_review_and_more'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=16)),
                ('is_subscription', models.BooleanField(default=False)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField()),
                ('account_amount_minor', models.PositiveBigIntegerField()),
                ('merchant', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField(blank=True, max_length=5000)),
                ('base_amount_minor', models.PositiveBigIntegerField()),
                ('base_currency', models.CharField(max_length=3)),
                ('rate_snapshot', models.DecimalField(decimal_places=12, max_digits=28)),
                ('rate_source', models.CharField(max_length=80)),
                ('rate_effective_at', models.DateTimeField()),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom interval')], max_length=16)),
                ('custom_interval_unit', models.CharField(blank=True, choices=[('day', 'Days'), ('week', 'Weeks'), ('month', 'Months'), ('year', 'Years')], max_length=8)),
                ('custom_interval_count', models.PositiveSmallIntegerField(default=1)),
                ('time_zone', models.CharField(max_length=64)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('local_time', models.TimeField()),
                ('anchor_day', models.PositiveSmallIntegerField()),
                ('anchor_month', models.PositiveSmallIntegerField()),
                ('next_due_on', models.DateField(db_index=True)),
                ('next_due_at', models.DateTimeField(db_index=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=12)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_provider', models.CharField(blank=True, max_length=160)),
                ('trial_ends_on', models.DateField(blank=True, null=True)),
                ('cancellation_url', models.URLField(blank=True, max_length=500)),
                ('subscription_note', models.TextField(blank=True, max_length=2000)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rules', to='ledger.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rules', to='ledger.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rules_created', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rules_edited', to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rules', to='ledger.tracker')),
            ],
            options={
                'ordering': ('next_due_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RecurringOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('occurrence_key', models.CharField(max_length=64, unique=True)),
                ('due_on', models.DateField()),
                ('scheduled_for', models.DateTimeField()),
                ('rule_version', models.PositiveBigIntegerField()),
                ('state', models.CharField(choices=[('posted', 'Posted'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=12)),
                ('materialized_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_occurrences', to='ledger.tracker')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_occurrence', to='ledger.transaction')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='planning.recurringrule')),
            ],
            options={
                'ordering': ('-scheduled_for',),
            },
        ),
        migrations.CreateModel(
            name='RecurringRuleRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_version', models.PositiveBigIntegerField()),
                ('reason', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=16)),
                ('is_subscription', models.BooleanField()),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField()),
                ('account_amount_minor', models.PositiveBigIntegerField()),
                ('merchant', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField(blank=True, max_length=5000)),
                ('base_amount_minor', models.PositiveBigIntegerField()),
                ('base_currency', models.CharField(max_length=3)),
                ('rate_snapshot', models.DecimalField(decimal_places=12, max_digits=28)),
                ('rate_source', models.CharField(max_length=80)),
                ('rate_effective_at', models.DateTimeField()),
                ('cadence', models.CharField(max_length=16)),
                ('custom_interval_unit', models.CharField(blank=True, max_length=8)),
                ('custom_interval_count', models.PositiveSmallIntegerField()),
                ('time_zone', models.CharField(max_length=64)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('local_time', models.TimeField()),
                ('next_due_on', models.DateField()),
                ('next_due_at', models.DateTimeField()),
                ('subscription_provider', models.CharField(blank=True, max_length=160)),
                ('trial_ends_on', models.DateField(blank=True, null=True)),
                ('cancellation_url', models.URLField(blank=True, max_length=500)),
                ('subscription_note', models.TextField(blank=True, max_length=2000)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rule_revisions', to='ledger.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rule_revisions', to='ledger.category')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rule_revisions_recorded', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='planning.recurringrule')),
            ],
            options={
                'ordering': ('-recorded_version',),
            },
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['tracker', 'state', 'next_due_at'], name='planning_re_tracker_91202d_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['tracker', 'is_subscription', 'deleted_at'], name='planning_re_tracker_928ea4_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('expense', 'income'))), name='recurring_kind_expense_or_income'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='recurring_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('account_amount_minor__gt', 0)), name='recurring_account_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount_minor__gt', 0)), name='recurring_base_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='recurring_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('next_due_on__gte', models.F('starts_on'))), name='recurring_next_due_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cadence', 'custom'), ('custom_interval_count__gte', 2), ('custom_interval_unit__gt', '')), models.Q(models.Q(('cadence', 'custom'), _negated=True), ('custom_interval_count', 1), ('custom_interval_unit', '')), _connector='OR'), name='recurring_custom_interval_shape'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('anchor_day__gte', 1), ('anchor_day__lte', 31)), name='recurring_anchor_day_range'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('anchor_month__gte', 1), ('anchor_month__lte', 12)), name='recurring_anchor_month_range'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('is_subscription', False), models.Q(('subscription_provider', ''), _negated=True), _connector='OR'), name='subscription_provider_required'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('paused_at__isnull', True), ('state', 'active')), models.Q(('ended_at__isnull', True), ('paused_at__isnull', False), ('state', 'paused')), models.Q(('ended_at__isnull', False), ('state', 'ended')), _connector='OR'), name='recurring_state_timestamp_shape'),
        ),
        migrations.AddIndex(
            model_name='recurringoccurrence',
            index=models.Index(fields=['tracker', 'state', 'scheduled_for'], name='planning_re_tracker_81e2f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringoccurrence',
            constraint=models.UniqueConstraint(fields=('rule', 'due_on'), name='unique_recurring_occurrence_due'),
        ),
        migrations.AddConstraint(
            model_name='recurringoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('error_code', ''), ('materialized_at__isnull', False), ('skipped_at__isnull', True), ('state', 'posted'), ('transaction__isnull', False)), models.Q(('error_code', ''), ('materialized_at__isnull', True), ('skipped_at__isnull', False), ('state', 'skipped'), ('transaction__isnull', True)), models.Q(('materialized_at__isnull', True), ('skipped_at__isnull', True), ('state', 'failed'), ('transaction__isnull', True)), _connector='OR'), name='recurring_occurrence_state_shape'),
        ),
        migrations.AddConstraint(
            model_name='recurringrulerevision',
            constraint=models.UniqueConstraint(fields=('rule', 'recorded_version'), name='unique_recurring_rule_recorded_version'),
        ),
    ]
