# Generated by Django 5.2.17 on 2026-08-09 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_transaction_card_label_transaction_needs_review_and_more'),
        ('planning', '0002_recurringrule_recurringoccurrence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recurringoccurrence',
            name='recurring_occurrence_state_shape',
        ),
        migrations.RemoveConstraint(
            model_name='recurringrule',
            name='recurring_custom_interval_shape',
        ),
        migrations.AddConstraint(
            model_name='recurringoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('error_code', ''), ('materialized_at__isnull', False), ('skipped_at__isnull', True), ('state', 'posted'), ('transaction__isnull', False)), models.Q(('error_code', ''), ('materialized_at__isnull', True), ('skipped_at__isnull', False), ('state', 'skipped'), ('transaction__isnull', True)), models.Q(('materialized_at__isnull', True), ('skipped_at__isnull', True), ('state', 'failed'), ('transaction__isnull', True), models.Q(('error_code', ''), _negated=True)), _connector='OR'), name='recurring_occurrence_state_shape'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cadence', 'custom'), ('custom_interval_count__gte', 2), ('custom_interval_count__lte', 365), ('custom_interval_unit__gt', '')), models.Q(models.Q(('cadence', 'custom'), _negated=True), ('custom_interval_count', 1), ('custom_interval_unit', '')), _connector='OR'), name='recurring_custom_interval_shape'),
        ),
    ]
