# Generated by Django 5.2.17 on 2026-08-13 14:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0003_transaction_card_label_transaction_needs_review_and_more"),
        (
            "planning",
            "0003_remove_recurringoccurrence_recurring_occurrence_state_shape_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("name", models.CharField(max_length=120)),
                ("principal_minor", models.PositiveBigIntegerField()),
                ("interest_minor", models.PositiveBigIntegerField(default=0)),
                ("fees_minor", models.PositiveBigIntegerField(default=0)),
                ("planned_total_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("currency_exponent", models.PositiveSmallIntegerField()),
                ("installment_count", models.PositiveSmallIntegerField()),
                (
                    "planned_installment_minor",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=12,
                    ),
                ),
                ("time_zone", models.CharField(max_length=64)),
                ("starts_on", models.DateField()),
                ("anchor_day", models.PositiveSmallIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paid_off", "Paid off"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("revision_number", models.PositiveIntegerField(default=1)),
                ("paid_off_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_plans",
                        to="ledger.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_plans",
                        to="ledger.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_plans_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_plans",
                        to="ledger.tracker",
                    ),
                ),
            ],
            options={"ordering": ("starts_on", "created_at")},
        ),
        migrations.CreateModel(
            name="InstallmentPlanRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision_number", models.PositiveIntegerField()),
                ("recorded_plan_version", models.PositiveBigIntegerField()),
                ("reason", models.CharField(max_length=24)),
                ("name", models.CharField(max_length=120)),
                ("principal_minor", models.PositiveBigIntegerField()),
                ("interest_minor", models.PositiveBigIntegerField()),
                ("fees_minor", models.PositiveBigIntegerField()),
                ("planned_total_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("currency_exponent", models.PositiveSmallIntegerField()),
                ("installment_count", models.PositiveSmallIntegerField()),
                (
                    "planned_installment_minor",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("cadence", models.CharField(max_length=12)),
                ("time_zone", models.CharField(max_length=64)),
                ("starts_on", models.DateField()),
                ("anchor_day", models.PositiveSmallIntegerField()),
                ("remaining_minor", models.PositiveBigIntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_plan_revisions",
                        to="ledger.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_plan_revisions",
                        to="ledger.category",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_plan_revisions_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="planning.installmentplan",
                    ),
                ),
            ],
            options={"ordering": ("-revision_number",)},
        ),
        migrations.CreateModel(
            name="InstallmentScheduleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("revision_number", models.PositiveIntegerField()),
                ("sequence", models.PositiveSmallIntegerField()),
                ("original_due_on", models.DateField()),
                ("due_on", models.DateField()),
                ("planned_principal_minor", models.PositiveBigIntegerField()),
                ("planned_interest_minor", models.PositiveBigIntegerField(default=0)),
                ("planned_fees_minor", models.PositiveBigIntegerField(default=0)),
                ("planned_total_minor", models.PositiveBigIntegerField()),
                ("paid_minor", models.PositiveBigIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("partially_paid", "Partially paid"),
                            ("paid", "Paid"),
                            ("skipped", "Skipped"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_items",
                        to="planning.installmentplan",
                    ),
                ),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_schedule_items",
                        to="ledger.tracker",
                    ),
                ),
            ],
            options={"ordering": ("sequence",)},
        ),
        migrations.CreateModel(
            name="InstallmentPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("applied_amount_minor", models.PositiveBigIntegerField()),
                ("overpayment_minor", models.PositiveBigIntegerField(default=0)),
                ("extra_payment", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_payments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_payments",
                        to="ledger.tracker",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_payment",
                        to="ledger.transaction",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="planning.installmentplan",
                    ),
                ),
                (
                    "schedule_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="planning.installmentscheduleitem",
                    ),
                ),
            ],
            options={"ordering": ("applied_at", "created_at")},
        ),
        migrations.CreateModel(
            name="InstallmentScheduleItemRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan_revision_number", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=24)),
                ("due_on", models.DateField()),
                ("state", models.CharField(max_length=20)),
                ("paid_minor", models.PositiveBigIntegerField()),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_schedule_revisions_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="planning.installmentscheduleitem",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddIndex(
            model_name="installmentplan",
            index=models.Index(
                fields=["tracker", "state", "starts_on"],
                name="planning_in_tracker_9f9193_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="installmentplan",
            index=models.Index(
                fields=["tracker", "archived_at", "deleted_at"],
                name="planning_in_tracker_4aa396_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(principal_minor__gt=0),
                name="installment_principal_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(planned_total_minor__gt=0),
                name="installment_total_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    planned_total_minor=models.F("principal_minor")
                    + models.F("interest_minor")
                    + models.F("fees_minor")
                ),
                name="installment_total_matches_terms",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(installment_count__gte=1, installment_count__lte=600),
                name="installment_count_between_1_and_600",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(anchor_day__gte=1, anchor_day__lte=31),
                name="installment_anchor_day_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(planned_installment_minor__isnull=True)
                | models.Q(planned_installment_minor__gt=0),
                name="installment_planned_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplan",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        state="active",
                        paid_off_at__isnull=True,
                        cancelled_at__isnull=True,
                    )
                    | models.Q(
                        state="paid_off",
                        paid_off_at__isnull=False,
                        cancelled_at__isnull=True,
                    )
                    | models.Q(
                        state="cancelled",
                        paid_off_at__isnull=True,
                        cancelled_at__isnull=False,
                    )
                ),
                name="installment_state_timestamp_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplanrevision",
            constraint=models.UniqueConstraint(
                fields=("plan", "revision_number"),
                name="unique_installment_plan_revision",
            ),
        ),
        migrations.AddIndex(
            model_name="installmentscheduleitem",
            index=models.Index(
                fields=["plan", "superseded_at", "due_on"],
                name="planning_in_plan_id_36d253_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentscheduleitem",
            constraint=models.UniqueConstraint(
                fields=("plan", "revision_number", "sequence"),
                name="unique_installment_schedule_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentscheduleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(sequence__gte=1),
                name="installment_schedule_sequence_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentscheduleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(planned_total_minor__gt=0),
                name="installment_schedule_total_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentscheduleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    planned_total_minor=models.F("planned_principal_minor")
                    + models.F("planned_interest_minor")
                    + models.F("planned_fees_minor")
                ),
                name="installment_schedule_total_matches_parts",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentscheduleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(paid_minor__lte=models.F("planned_total_minor")),
                name="installment_schedule_paid_not_above_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentscheduleitem",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(state="planned", paid_minor=0, skipped_at__isnull=True)
                    | (
                        models.Q(
                            state="partially_paid",
                            paid_minor__gt=0,
                            skipped_at__isnull=True,
                        )
                        & models.Q(paid_minor__lt=models.F("planned_total_minor"))
                    )
                    | models.Q(
                        state="paid",
                        paid_minor=models.F("planned_total_minor"),
                        skipped_at__isnull=True,
                    )
                    | models.Q(state="skipped", paid_minor=0, skipped_at__isnull=False)
                ),
                name="installment_schedule_state_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(amount_minor__gt=0),
                name="installment_payment_amount_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(applied_amount_minor__gt=0),
                name="installment_payment_applied_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    amount_minor=models.F("applied_amount_minor") + models.F("overpayment_minor")
                ),
                name="installment_payment_amount_matches_application",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(extra_payment=True) | models.Q(schedule_item__isnull=False),
                name="regular_installment_payment_has_schedule_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentscheduleitemrevision",
            constraint=models.UniqueConstraint(
                fields=("schedule_item", "plan_revision_number"),
                name="unique_installment_schedule_item_revision",
            ),
        ),
    ]
