import Foundation
import SwiftData
import SwiftUI
import UniformTypeIdentifiers

struct ExportSettingsView: View {
    let scopeKey: String

    @EnvironmentObject private var session: SessionController
    @EnvironmentObject private var sync: SyncController
    @Query private var trackers: [LocalTracker]
    @Query private var accounts: [LocalAccount]
    @StateObject private var controller = ExportController()
    @State private var selectedTrackerID: UUID?
    @State private var selectedAccountID: UUID?
    @State private var selectedFormat = ExportFormat.csv
    @State private var includeNotes = true
    @State private var document: ExportFileDocument?
    @State private var showingExporter = false

    init(scopeKey: String) {
        self.scopeKey = scopeKey
        _trackers = Query(
            filter: #Predicate { $0.scopeKey == scopeKey },
            sort: \LocalTracker.sortOrder
        )
        _accounts = Query(
            filter: #Predicate { $0.scopeKey == scopeKey },
            sort: \LocalAccount.name
        )
    }

    private var visibleTrackers: [LocalTracker] {
        trackers.filter { $0.deletedAt == nil && $0.accessRevokedAt == nil }
    }

    private var selectedTracker: LocalTracker? {
        visibleTrackers.first { $0.id == selectedTrackerID } ?? visibleTrackers.first
    }

    private var trackerAccounts: [LocalAccount] {
        guard let tracker = selectedTracker else { return [] }
        return accounts.filter {
            $0.trackerID == tracker.id && $0.deletedAt == nil && $0.archivedAt == nil
        }
    }

    var body: some View {
        Form {
            Section {
                if visibleTrackers.isEmpty {
                    Label("No tracker is available", systemImage: "square.stack.3d.up.slash")
                } else {
                    Picker("Tracker", selection: $selectedTrackerID) {
                        ForEach(visibleTrackers) { tracker in
                            Text(tracker.name).tag(Optional(tracker.id))
                        }
                    }
                    Picker("Format", selection: $selectedFormat) {
                        ForEach(ExportFormat.allCases) { format in
                            Text(format.displayName).tag(format)
                        }
                    }
                    Picker("Account filter", selection: $selectedAccountID) {
                        Text("All accounts").tag(UUID?.none)
                        ForEach(trackerAccounts) { account in
                            Text(account.name).tag(Optional(account.id))
                        }
                    }
                    Toggle("Include notes", isOn: $includeNotes)
                    Button {
                        Task { await createExport() }
                    } label: {
                        if controller.isWorking {
                            ProgressView()
                        } else {
                            Label("Generate export", systemImage: "square.and.arrow.down")
                        }
                    }
                    .disabled(controller.isWorking || sync.isRunning || selectedTracker == nil)
                }
            } header: {
                Text("Create export")
            } footer: {
                Text("Exports are generated by your server, stored privately, and expire automatically. Downloads are available only to the requester.")
            }

            if let errorMessage = controller.errorMessage {
                Section("Export notice") {
                    Label(errorMessage, systemImage: "exclamationmark.triangle")
                    if let requestID = controller.requestID {
                        Text(String(format: String(localized: "Request ID format"), requestID))
                            .font(.caption.monospaced())
                            .textSelection(.enabled)
                    }
                    Button("Retry") {
                        Task { await loadExports() }
                    }
                    .disabled(controller.isWorking)
                }
            }

            Section("Recent exports") {
                if controller.isWorking && controller.jobs.isEmpty {
                    HStack {
                        ProgressView()
                        Text("Loading exports…")
                    }
                } else if controller.jobs.isEmpty {
                    Text("No exports yet")
                        .foregroundStyle(.secondary)
                } else {
                    ForEach(controller.jobs) { job in
                        ExportJobRow(
                            job: job,
                            trackerName: trackerName(for: job.trackerID),
                            isDownloading: controller.downloadingID == job.id,
                            download: {
                                Task { await download(job) }
                            }
                        )
                    }
                }
            }
        }
        .navigationTitle("Exports")
        .task {
            if selectedTrackerID == nil {
                selectedTrackerID = visibleTrackers.first?.id
            }
            await loadExports()
        }
        .refreshable {
            await loadExports()
        }
        .onChange(of: selectedTrackerID) { _, _ in
            selectedAccountID = nil
        }
        .fileExporter(
            isPresented: $showingExporter,
            document: document,
            contentType: document?.contentType ?? .data,
            defaultFilename: document?.filename ?? "miravo-export"
        ) { _ in
            document = nil
            controller.clearDownloadedExport()
        }
        .onChange(of: controller.downloadedExport) { _, newValue in
            guard let newValue else { return }
            document = ExportFileDocument(export: newValue)
            showingExporter = true
        }
    }

    private func trackerName(for trackerID: UUID) -> String {
        trackers.first { $0.id == trackerID }?.name ?? String(localized: "Unavailable")
    }

    private func createExport() async {
        guard let tracker = selectedTracker,
              let authentication = await authenticationContext()
        else { return }
        _ = await controller.create(
            trackerID: tracker.id,
            format: selectedFormat,
            accountID: selectedAccountID,
            includeNotes: includeNotes,
            authentication: authentication
        )
    }

    private func loadExports() async {
        guard let authentication = await authenticationContext() else { return }
        await controller.load(authentication: authentication)
    }

    private func download(_ job: ExportJobSummary) async {
        guard let authentication = await authenticationContext() else { return }
        _ = await controller.download(job: job, authentication: authentication)
    }

    private func authenticationContext() async -> SyncAuthenticationContext? {
        do {
            guard let authentication = try await session.synchronizationContext() else {
                controller.presentAuthenticationUnavailable()
                return nil
            }
            return authentication
        } catch {
            controller.presentAuthenticationUnavailable()
            return nil
        }
    }
}

private struct ExportJobRow: View {
    let job: ExportJobSummary
    let trackerName: String
    let isDownloading: Bool
    let download: () -> Void

    var body: some View {
        VStack(alignment: .leading, spacing: LedgerTheme.smallSpacing) {
            HStack {
                Text(job.format.displayName)
                    .font(.headline)
                Spacer()
                Text(statusText)
                    .font(.caption)
                    .foregroundStyle(statusColor)
            }
            Text(trackerName)
                .font(.subheadline)
                .foregroundStyle(.secondary)
            LabeledContent("Size", value: ByteCountFormatter.string(
                fromByteCount: job.byteCount,
                countStyle: .file
            ))
            if let expirationDate = job.expirationDate {
                LabeledContent("Expires") {
                    Text(expirationDate, format: .dateTime.day().month().year().hour().minute())
                }
            }
            Text(verbatim: job.checksumSHA256)
                .font(.caption.monospaced())
                .lineLimit(2)
                .textSelection(.enabled)
                .accessibilityLabel("SHA-256 checksum")
            Button {
                download()
            } label: {
                if isDownloading {
                    ProgressView()
                } else {
                    Label("Download verified file", systemImage: "checkmark.shield")
                }
            }
            .disabled(job.state != .ready || job.isExpired() || isDownloading)
        }
        .accessibilityElement(children: .combine)
        .accessibilityLabel("\(job.format.displayName), \(trackerName), \(statusText)")
    }

    private var statusText: String {
        if job.isExpired() { return String(localized: "Expired") }
        switch job.state {
        case .ready:
            return String(localized: "Ready")
        case .failed:
            return String(localized: "Failed")
        case .expired:
            return String(localized: "Expired")
        }
    }

    private var statusColor: Color {
        switch job.state {
        case .ready:
            return .green
        case .failed:
            return .red
        case .expired:
            return .secondary
        }
    }
}

struct ExportFileDocument: FileDocument {
    static var readableContentTypes: [UTType] { [.data] }
    static var writableContentTypes: [UTType] { [.commaSeparatedText, .pdf, .json, .data] }

    let filename: String
    let contentType: UTType
    let data: Data

    init(export: DownloadedExport) {
        filename = export.filename
        switch export.format {
        case .csv:
            contentType = .commaSeparatedText
        case .pdf:
            contentType = .pdf
        case .full:
            contentType = .json
        }
        data = export.data
    }

    init(configuration: ReadConfiguration) throws {
        filename = "miravo-export"
        contentType = configuration.contentType
        data = configuration.file.regularFileContents ?? Data()
    }

    func fileWrapper(configuration: WriteConfiguration) throws -> FileWrapper {
        FileWrapper(regularFileWithContents: data)
    }
}
